
package com.ipn.desktop;

import com.ipn.persistance.support.AlumnoImplements;
import com.ipn.persistance.support.CalificacionImplements;
import com.ipn.persistance.support.CentrodetrabajoImplements;
import com.ipn.persistance.support.ExamenImplements;
import com.ipn.persistance.support.MateriaImplements;
import com.ipn.persistance.support.PreguntaImplements;
import com.ipn.persistance.support.RespuestaImplements;
import javax.persistence.EntityManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Al3x
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        dtm = new DefaultTableModel(0, 0);
        dtm.setColumnIdentifiers(new String[] { "Id", "Hecho" });
        this.jTable1.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        LoginMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        ConsultasMenu = new javax.swing.JMenu();
        AlumnojMenu = new javax.swing.JMenuItem();
        CarrerasjMenu = new javax.swing.JMenuItem();
        CTrabajojMenu = new javax.swing.JMenuItem();
        CalijMenu = new javax.swing.JMenuItem();
        ExamenjMenu = new javax.swing.JMenuItem();
        MateriasjMenu = new javax.swing.JMenuItem();
        PreguntasjMenu = new javax.swing.JMenuItem();
        RespuestasjMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        LoginMenuItem.setMnemonic('a');
        LoginMenuItem.setText("Login");
        fileMenu.add(LoginMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        ConsultasMenu.setText("Consultas");

        AlumnojMenu.setText("Alumnos");
        AlumnojMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlumnojMenuActionPerformed(evt);
            }
        });
        ConsultasMenu.add(AlumnojMenu);

        CarrerasjMenu.setText("Carreras");
        CarrerasjMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrerasjMenuActionPerformed(evt);
            }
        });
        ConsultasMenu.add(CarrerasjMenu);

        CTrabajojMenu.setText("Centro de Trabajo");
        CTrabajojMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTrabajojMenuActionPerformed(evt);
            }
        });
        ConsultasMenu.add(CTrabajojMenu);

        CalijMenu.setText("Calificaciones");
        CalijMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalijMenuActionPerformed(evt);
            }
        });
        ConsultasMenu.add(CalijMenu);

        ExamenjMenu.setText("Examenes");
        ExamenjMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamenjMenuActionPerformed(evt);
            }
        });
        ConsultasMenu.add(ExamenjMenu);

        MateriasjMenu.setText("Materias");
        MateriasjMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MateriasjMenuActionPerformed(evt);
            }
        });
        ConsultasMenu.add(MateriasjMenu);

        PreguntasjMenu.setText("Preguntas");
        ConsultasMenu.add(PreguntasjMenu);

        RespuestasjMenu.setText("Respuestas");
        ConsultasMenu.add(RespuestasjMenu);

        menuBar.add(ConsultasMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void AlumnojMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlumnojMenuActionPerformed
        // TODO add your handling code here:
        dtm = new DefaultTableModel(0, 0);
        dtm.setColumnIdentifiers(new String[] { "Matricula", "Nombre","Apellidos","Fecha de nacimiento","Sexo","Email" });
        this.jTable1.setModel(dtm);
    }//GEN-LAST:event_AlumnojMenuActionPerformed

    private void CarrerasjMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrerasjMenuActionPerformed
        // TODO add your handling code here:
        dtm = new DefaultTableModel(0, 0);
        dtm.setColumnIdentifiers(new String[] { "Nombre", "Duracion" });
        this.jTable1.setModel(dtm);
    }//GEN-LAST:event_CarrerasjMenuActionPerformed

    private void CTrabajojMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTrabajojMenuActionPerformed
        // TODO add your handling code here:
         dtm = new DefaultTableModel(0, 0);
        dtm.setColumnIdentifiers(new String[] { "Nombre" });
        this.jTable1.setModel(dtm);
    }//GEN-LAST:event_CTrabajojMenuActionPerformed

    private void CalijMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalijMenuActionPerformed
        // TODO add your handling code here:
         dtm = new DefaultTableModel(0, 0);
        dtm.setColumnIdentifiers(new String[] { "Puntaje" });
        this.jTable1.setModel(dtm);
    }//GEN-LAST:event_CalijMenuActionPerformed

    private void ExamenjMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamenjMenuActionPerformed
        // TODO add your handling code here:
        dtm = new DefaultTableModel(0, 0);
        dtm.setColumnIdentifiers(new String[] { "Fecha" });
        this.jTable1.setModel(dtm);
    }//GEN-LAST:event_ExamenjMenuActionPerformed

    private void MateriasjMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MateriasjMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MateriasjMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    private EntityManager em;
    private AlumnoImplements alumnodao;
    private CalificacionImplements califdao;
    private CentrodetrabajoImplements centroTrabajo;
    private ExamenImplements examendao;
    private MateriaImplements materiadao;
    private PreguntaImplements preguntadao;
    private RespuestaImplements respuestadao;
    private DefaultTableModel dtm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlumnojMenu;
    private javax.swing.JMenuItem CTrabajojMenu;
    private javax.swing.JMenuItem CalijMenu;
    private javax.swing.JMenuItem CarrerasjMenu;
    private javax.swing.JMenu ConsultasMenu;
    private javax.swing.JMenuItem ExamenjMenu;
    private javax.swing.JMenuItem LoginMenuItem;
    private javax.swing.JMenuItem MateriasjMenu;
    private javax.swing.JMenuItem PreguntasjMenu;
    private javax.swing.JMenuItem RespuestasjMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
